spring:
  application:
    name: querySense

  datasource:
    app:
      jdbc-url: jdbc:postgresql://localhost:5440/querysense
      username: querysense
      password: querysense
      driver-class-name: org.postgresql.Driver
    analytics:
      jdbc-url: jdbc:postgresql://localhost:5440/analytics
      username: analytics_readonly
      password: readonly
      driver-class-name: org.postgresql.Driver
    analytics-admin:
      jdbc-url: jdbc:postgresql://localhost:5440/analytics
      username: querysense
      password: querysense
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5-coder:7b
          temperature: 0.0

server:
  port: 8084